Version: v1 #版本
Debug: true
Server:
    HostPort: 8080  # 端口
    ReadTimeout: 60
    WriteTimeout: 60

Mysql:
    Host: 127.0.0.1
    Port: 3306
    User: test
    Password: test@666666
    DbName: test
    TablePrefix: novel_
Redis:
    Host: 127.0.0.1
    Port: 6379
    DB: 0
    Username:
    Password:

Mongo:
    Host: localhost
    Port: 27017
    Auth: true #是否开启认证
    Username: root
    Password: root

JWT:
    Secret: aNGWnTH0yw69EoIi4TMocQH3qVu1ulSu
    ExpiresAt: 20  #过期时间(分钟)

CacheTokenKey: "token:%d" # redis 缓存token的key
